//! L5 + L6 parity gate (PLAN.md P1.17 — Phase 1 exit).
//!
//! Drives the Rust MS2 quantification engine ([`flashlfq_core::engine::run_msms`]) over the
//! Phase-1 corpus (`AllPSMs.psmtsv` + the two K562 mzMLs) and diffs its output against the
//! **real C#** goldens generated by `parity/csharp_golden/` (the actual `FlashLfqEngine`, MS2
//! path, default params, single-threaded):
//!
//! - **L5** `parity/golden/L5_chromatographic_peaks.tsv` — one row per `ChromatographicPeak`
//!   after error checking (per-(peptide, file) integrated intensity, apex scan/charge/pearson,
//!   mass error, etc.).
//! - **L6** `parity/golden/L6_peptide_intensities.tsv` — one row per (modified sequence, file)
//!   cell (the end-to-end peptide × file table).
//!
//! Both sides sort rows deterministically with the *same* comparator before a positional diff:
//! L5 by `(file_name, modified_sequence, apex_rt, intensity)` (NaN sorts last, exactly as the C#
//! generator's `ParseSortable` maps NaN → `double.MaxValue`); L6 by `(modified_sequence,
//! file_name)`. Comparison: integers / scan indices / charges / counts and all string columns
//! exact; floats relative `1e-6` (with `NaN == NaN`).

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use flashlfq_core::engine::{run_msms, Ms2QuantResult};
use flashlfq_core::isotopic_envelope::mz_to_mass_f32;
use flashlfq_core::psm_tsv::read_identifications;

const FILE_3: &str = "20100614_Velos1_TaGe_SA_K562_3";
const FILE_4: &str = "20100614_Velos1_TaGe_SA_K562_4";

/// `<repo>/mzLib/Test/FlashLFQ/TestData/<relative>`.
fn test_data(relative: &str) -> PathBuf {
    flashlfq_core::mzlib_test_data(relative)
}

/// `<repo>/rust/flashlfq-core/parity/golden/<relative>`.
fn golden(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("parity")
        .join("golden")
        .join(relative)
}

/// Reads a golden TSV into `(header, rows)`, each row a `Vec<String>` of tab-separated cells.
fn read_tsv(path: &PathBuf) -> (Vec<String>, Vec<Vec<String>>) {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("could not read golden {}: {e}", path.display()));
    let mut lines = text.lines();
    let header: Vec<String> = lines
        .next()
        .expect("golden has a header")
        .split('\t')
        .map(|s| s.to_string())
        .collect();
    let rows: Vec<Vec<String>> = lines
        .filter(|l| !l.is_empty())
        .map(|l| l.split('\t').map(|s| s.to_string()).collect())
        .collect();
    (header, rows)
}

/// Parses a golden double cell, mapping `"NaN"` to `f64::NAN` (C# `double.ToString("R")`).
fn parse_f64(cell: &str) -> f64 {
    if cell == "NaN" {
        f64::NAN
    } else {
        cell.parse::<f64>()
            .unwrap_or_else(|_| panic!("could not parse double cell '{cell}'"))
    }
}

/// The C# `ParseSortable`: parse, NaN → `f64::MAX` so NaN-keyed rows sort last.
fn sortable(cell: &str) -> f64 {
    let v = parse_f64(cell);
    if v.is_nan() {
        f64::MAX
    } else {
        v
    }
}

/// `|a-b| / max(|a|,|b|) < 1e-6`, with `NaN == NaN` and exact-equal (incl. both `0`) accepted.
fn floats_match(a: f64, b: f64) -> bool {
    if a.is_nan() && b.is_nan() {
        return true;
    }
    if a == b {
        return true;
    }
    if !a.is_finite() || !b.is_finite() {
        return false;
    }
    let denom = a.abs().max(b.abs());
    (a - b).abs() / denom < 1e-6
}

/// Distinct values of `iter`, preserving first-occurrence order, joined by `|`
/// (mirrors C# `string.Join("|", xs.Distinct())`).
fn distinct_join<'a>(iter: impl Iterator<Item = &'a str>) -> String {
    let mut seen: Vec<&str> = Vec::new();
    for x in iter {
        if !seen.contains(&x) {
            seen.push(x);
        }
    }
    seen.join("|")
}

/// Builds the file → mzML path map for the corpus.
fn file_to_mzml() -> HashMap<String, PathBuf> {
    let mut m = HashMap::new();
    m.insert(FILE_3.to_string(), test_data(&format!("{FILE_3}.mzML")));
    m.insert(FILE_4.to_string(), test_data(&format!("{FILE_4}.mzML")));
    m
}

/// Runs the engine once over the corpus.
fn run_engine() -> Ms2QuantResult {
    let ids = read_identifications(test_data("AllPSMs.psmtsv"))
        .expect("AllPSMs.psmtsv parses into identifications");
    run_msms(ids, &file_to_mzml()).expect("engine runs over the corpus")
}

/// Runs the engine over the corpus with a deterministic decoy flip (PLAN.md P2.2): distinct
/// modified sequences sorted (Rust `str` Ord == C# `StringComparer.Ordinal` for these ASCII
/// sequences), every 3rd one (`index % 3 == 0`) marked decoy — the *identical* rule the C# golden
/// generator applies before re-running the real engine.
fn run_engine_with_decoy_flip() -> Ms2QuantResult {
    let mut ids = read_identifications(test_data("AllPSMs.psmtsv"))
        .expect("AllPSMs.psmtsv parses into identifications");

    let mut distinct: Vec<String> = Vec::new();
    for id in &ids {
        if !distinct.contains(&id.modified_sequence) {
            distinct.push(id.modified_sequence.clone());
        }
    }
    distinct.sort();
    let decoy_set: HashSet<&str> = distinct
        .iter()
        .enumerate()
        .filter(|(i, _)| i % 3 == 0)
        .map(|(_, s)| s.as_str())
        .collect();

    for id in &mut ids {
        id.is_decoy = decoy_set.contains(id.modified_sequence.as_str());
    }

    run_msms(ids, &file_to_mzml()).expect("engine runs over the decoy-flipped corpus")
}

/// Builds the sorted Rust L6 rows `(modseq, file, intensity, rt, detection_type)` from results.
fn rust_l6_rows(result: &Ms2QuantResult) -> Vec<(String, String, f64, f64, String)> {
    let mut rows: Vec<(String, String, f64, f64, String)> = Vec::new();
    for (modseq, per_file) in &result.peptide_results.quant {
        for (file_name, quant) in per_file {
            rows.push((
                modseq.clone(),
                file_name.clone(),
                quant.intensity,
                quant.retention_time,
                quant.detection_type.as_str().to_string(),
            ));
        }
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
    rows
}

/// One L5 row as the typed values the golden columns hold (string columns kept verbatim).
struct L5Row {
    file_name: String,
    base_sequence: String,
    modified_sequence: String,
    monoisotopic_mass: f64,
    ms2_retention_time: f64,
    precursor_charge: i32,
    peak_intensity: f64,
    peak_rt_start: f64,
    peak_rt_apex: f64,
    peak_rt_end: f64,
    peak_mz: f64,
    apex_charge: i32,
    apex_scan_index: i32,
    apex_pearson: f64,
    num_charge_states: i64,
    mass_error: f64,
    split_rt: f64,
    num_ids_by_full_seq: i64,
    detection_type: String,
    decoy: bool,
}

/// Builds the Rust L5 rows from the engine's per-file error-checked peaks.
fn rust_l5_rows(result: &Ms2QuantResult) -> Vec<L5Row> {
    let mut rows: Vec<L5Row> = Vec::new();
    for (file_name, peaks) in &result.peaks_by_file {
        for peak in peaks {
            let first = peak
                .identifications
                .first()
                .expect("every MS2 peak carries at least one identification");

            let base_sequence =
                distinct_join(peak.identifications.iter().map(|i| i.base_sequence.as_str()));
            let modified_sequence = distinct_join(
                peak.identifications
                    .iter()
                    .map(|i| i.modified_sequence.as_str()),
            );

            let (rt_start, rt_apex, rt_end, peak_mz, apex_charge, apex_scan_index, apex_pearson) =
                match peak.apex {
                    Some(apex) => {
                        let rt_start = peak
                            .isotopic_envelopes
                            .iter()
                            .map(|e| e.indexed_peak.retention_time)
                            .fold(f32::INFINITY, f32::min)
                            as f64;
                        let rt_end = peak
                            .isotopic_envelopes
                            .iter()
                            .map(|e| e.indexed_peak.retention_time)
                            .fold(f32::NEG_INFINITY, f32::max)
                            as f64;
                        (
                            rt_start,
                            apex.indexed_peak.retention_time as f64,
                            rt_end,
                            apex.indexed_peak.m() as f64,
                            apex.charge_state,
                            apex.indexed_peak.zero_based_scan_index,
                            apex.pearson_correlation,
                        )
                    }
                    None => (
                        f64::NAN,
                        f64::NAN,
                        f64::NAN,
                        f64::NAN,
                        -1,
                        -1,
                        f64::NAN,
                    ),
                };

            rows.push(L5Row {
                file_name: file_name.clone(),
                base_sequence,
                modified_sequence,
                monoisotopic_mass: first.monoisotopic_mass,
                ms2_retention_time: first.ms2_retention_time_in_minutes,
                precursor_charge: first.precursor_charge_state,
                peak_intensity: peak.intensity,
                peak_rt_start: rt_start,
                peak_rt_apex: rt_apex,
                peak_rt_end: rt_end,
                peak_mz,
                apex_charge,
                apex_scan_index,
                apex_pearson,
                num_charge_states: peak.num_charge_states_observed as i64,
                mass_error: peak.mass_error,
                split_rt: peak.split_rt,
                num_ids_by_full_seq: peak.num_identifications_by_full_seq as i64,
                detection_type: peak.detection_type.as_str().to_string(),
                decoy: peak.decoy_peptide(),
            });
        }
    }
    rows
}

#[test]
fn l5_chromatographic_peaks_match_csharp_golden() {
    let result = run_engine();
    let mut rust_rows = rust_l5_rows(&result);

    let (header, golden_rows) = read_tsv(&golden("L5_chromatographic_peaks.tsv"));
    assert_eq!(header.len(), 20, "L5 golden header column count");

    assert_eq!(
        rust_rows.len(),
        golden_rows.len(),
        "L5 row count: rust {} vs golden {}",
        rust_rows.len(),
        golden_rows.len()
    );

    // Sort the Rust rows with the same comparator the C# generator uses:
    // file (ordinal), modified sequence (ordinal), apex RT (NaN last), intensity.
    rust_rows.sort_by(|a, b| {
        a.file_name
            .cmp(&b.file_name)
            .then_with(|| a.modified_sequence.cmp(&b.modified_sequence))
            .then_with(|| {
                let ar = if a.peak_rt_apex.is_nan() {
                    f64::MAX
                } else {
                    a.peak_rt_apex
                };
                let br = if b.peak_rt_apex.is_nan() {
                    f64::MAX
                } else {
                    b.peak_rt_apex
                };
                ar.partial_cmp(&br).unwrap()
            })
            .then_with(|| a.peak_intensity.partial_cmp(&b.peak_intensity).unwrap())
    });

    let mut golden_sorted = golden_rows.clone();
    // Golden columns: [8] apex RT, [6] intensity, [0] file, [2] modified sequence.
    golden_sorted.sort_by(|a, b| {
        a[0].cmp(&b[0])
            .then_with(|| a[2].cmp(&b[2]))
            .then_with(|| sortable(&a[8]).partial_cmp(&sortable(&b[8])).unwrap())
            .then_with(|| sortable(&a[6]).partial_cmp(&sortable(&b[6])).unwrap())
    });

    let mut mismatches: Vec<String> = Vec::new();
    let mut all_msms = true;
    for (i, (r, g)) in rust_rows.iter().zip(golden_sorted.iter()).enumerate() {
        let mut row_errs: Vec<String> = Vec::new();

        macro_rules! str_eq {
            ($got:expr, $col:expr, $name:expr) => {
                if $got != g[$col] {
                    row_errs.push(format!("{}: rust '{}' vs golden '{}'", $name, $got, g[$col]));
                }
            };
        }
        macro_rules! float_close {
            ($got:expr, $col:expr, $name:expr) => {
                if !floats_match($got, parse_f64(&g[$col])) {
                    row_errs.push(format!(
                        "{}: rust {} vs golden {}",
                        $name, $got, g[$col]
                    ));
                }
            };
        }
        macro_rules! int_eq {
            ($got:expr, $col:expr, $name:expr) => {
                if $got.to_string() != g[$col] {
                    row_errs.push(format!("{}: rust {} vs golden {}", $name, $got, g[$col]));
                }
            };
        }

        str_eq!(r.file_name, 0, "file_name");
        str_eq!(r.base_sequence, 1, "base_sequence");
        str_eq!(r.modified_sequence, 2, "modified_sequence");
        float_close!(r.monoisotopic_mass, 3, "monoisotopic_mass");
        float_close!(r.ms2_retention_time, 4, "ms2_retention_time");
        int_eq!(r.precursor_charge, 5, "precursor_charge");
        float_close!(r.peak_intensity, 6, "peak_intensity");
        float_close!(r.peak_rt_start, 7, "peak_rt_start");
        float_close!(r.peak_rt_apex, 8, "peak_rt_apex");
        float_close!(r.peak_rt_end, 9, "peak_rt_end");
        float_close!(r.peak_mz, 10, "peak_mz");
        int_eq!(r.apex_charge, 11, "apex_charge");
        int_eq!(r.apex_scan_index, 12, "apex_scan_index");
        float_close!(r.apex_pearson, 13, "apex_pearson");
        int_eq!(r.num_charge_states, 14, "num_charge_states");
        float_close!(r.mass_error, 15, "mass_error");
        float_close!(r.split_rt, 16, "split_rt");
        int_eq!(r.num_ids_by_full_seq, 17, "num_ids_by_full_seq");
        str_eq!(r.detection_type, 18, "detection_type");
        // decoy: rust bool "false"/"true" vs C# "False"/"True".
        let decoy_str = if r.decoy { "True" } else { "False" };
        if decoy_str != g[19] {
            row_errs.push(format!("decoy: rust {} vs golden {}", decoy_str, g[19]));
        }

        if r.detection_type != "MSMS" {
            all_msms = false;
        }

        if !row_errs.is_empty() && mismatches.len() < 20 {
            mismatches.push(format!(
                "row {i} ({}|{}): {}",
                r.file_name,
                r.modified_sequence,
                row_errs.join("; ")
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "L5 mismatches ({} rows shown):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
    assert!(all_msms, "L5 sanity: every peak's detection type should be MSMS");

    // Cross-check: every Rust apex mass error is the recomputed apex-mass ppm vs peakfinding mass.
    // (Sanity that the apex/charge wiring is internally consistent.)
    for peak in result.peaks_by_file.values().flatten() {
        if let Some(apex) = peak.apex {
            let _ = mz_to_mass_f32(apex.indexed_peak.m(), apex.charge_state);
        }
    }
}

#[test]
fn l6_peptide_intensities_match_csharp_golden() {
    let result = run_engine();

    // Build Rust L6 rows: one per (modified sequence, file) in the quant table.
    let rust_rows = rust_l6_rows(&result);

    let (header, golden_rows) = read_tsv(&golden("L6_peptide_intensities.tsv"));
    assert_eq!(header.len(), 5, "L6 golden header column count");
    assert_eq!(
        rust_rows.len(),
        golden_rows.len(),
        "L6 row count: rust {} vs golden {}",
        rust_rows.len(),
        golden_rows.len()
    );

    let mut golden_sorted = golden_rows.clone();
    golden_sorted.sort_by(|a, b| a[0].cmp(&b[0]).then_with(|| a[1].cmp(&b[1])));

    let mut mismatches: Vec<String> = Vec::new();
    // Detection-type histogram for the sanity targets.
    let mut hist: HashMap<String, usize> = HashMap::new();
    for (r, g) in rust_rows.iter().zip(golden_sorted.iter()) {
        *hist.entry(r.4.clone()).or_default() += 1;
        let mut errs: Vec<String> = Vec::new();
        if r.0 != g[0] {
            errs.push(format!("modified_sequence: rust '{}' vs golden '{}'", r.0, g[0]));
        }
        if r.1 != g[1] {
            errs.push(format!("file_name: rust '{}' vs golden '{}'", r.1, g[1]));
        }
        if !floats_match(r.2, parse_f64(&g[2])) {
            errs.push(format!("intensity: rust {} vs golden {}", r.2, g[2]));
        }
        if !floats_match(r.3, parse_f64(&g[3])) {
            errs.push(format!("retention_time: rust {} vs golden {}", r.3, g[3]));
        }
        if r.4 != g[4] {
            errs.push(format!("detection_type: rust '{}' vs golden '{}'", r.4, g[4]));
        }
        if !errs.is_empty() && mismatches.len() < 20 {
            mismatches.push(format!("({}|{}): {}", r.0, r.1, errs.join("; ")));
        }
    }

    assert!(
        mismatches.is_empty(),
        "L6 mismatches ({} shown):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );

    // Sanity targets from PLAN.md P1.17 (detection-type mix across the 708 cells).
    println!("L6 detection-type histogram: {hist:?}");
    assert_eq!(hist.get("MSMS").copied().unwrap_or(0), 450, "MSMS cells");
    assert_eq!(
        hist.get("NotDetected").copied().unwrap_or(0),
        223,
        "NotDetected cells"
    );
    assert_eq!(
        hist.get("MSMSIdentifiedButNotQuantified").copied().unwrap_or(0),
        33,
        "MSMSIdentifiedButNotQuantified cells"
    );
    assert_eq!(
        hist.get("MSMSAmbiguousPeakfinding").copied().unwrap_or(0),
        2,
        "MSMSAmbiguousPeakfinding cells"
    );
}

/// L6 decoy parity (PLAN.md P2.2 — FDR / decoy hardening). With a deterministic third of the
/// modified sequences flipped to decoy (the same rule on both sides), the Rust peptide×file table
/// must match the **real C# engine** decoy golden. This exercises the decoy split introduced in
/// P2.2: decoy modseqs sit in the quantify set (so they still drive error-checking merges) but get
/// no output row, while the surviving target rows match C# cell-for-cell.
#[test]
fn l6_decoy_flip_matches_csharp_golden() {
    let result = run_engine_with_decoy_flip();
    let rust_rows = rust_l6_rows(&result);

    let (header, golden_rows) = read_tsv(&golden("L6_peptide_intensities_decoy.tsv"));
    assert_eq!(header.len(), 5, "L6 decoy golden header column count");
    assert_eq!(
        rust_rows.len(),
        golden_rows.len(),
        "L6 decoy row count: rust {} vs golden {} (expected non-decoy modseqs × files)",
        rust_rows.len(),
        golden_rows.len()
    );

    let mut golden_sorted = golden_rows.clone();
    golden_sorted.sort_by(|a, b| a[0].cmp(&b[0]).then_with(|| a[1].cmp(&b[1])));

    // No decoy modified sequence should appear as an output row.
    let mut distinct: Vec<String> = Vec::new();
    {
        let ids = read_identifications(test_data("AllPSMs.psmtsv")).unwrap();
        for id in &ids {
            if !distinct.contains(&id.modified_sequence) {
                distinct.push(id.modified_sequence.clone());
            }
        }
    }
    distinct.sort();
    let decoy_set: HashSet<&str> = distinct
        .iter()
        .enumerate()
        .filter(|(i, _)| i % 3 == 0)
        .map(|(_, s)| s.as_str())
        .collect();
    for (modseq, _, _, _, _) in &rust_rows {
        assert!(
            !decoy_set.contains(modseq.as_str()),
            "decoy modseq {modseq:?} must not appear in the output table"
        );
    }

    let mut mismatches: Vec<String> = Vec::new();
    for (r, g) in rust_rows.iter().zip(golden_sorted.iter()) {
        let mut errs: Vec<String> = Vec::new();
        if r.0 != g[0] {
            errs.push(format!("modified_sequence: rust '{}' vs golden '{}'", r.0, g[0]));
        }
        if r.1 != g[1] {
            errs.push(format!("file_name: rust '{}' vs golden '{}'", r.1, g[1]));
        }
        if !floats_match(r.2, parse_f64(&g[2])) {
            errs.push(format!("intensity: rust {} vs golden {}", r.2, g[2]));
        }
        if !floats_match(r.3, parse_f64(&g[3])) {
            errs.push(format!("retention_time: rust {} vs golden {}", r.3, g[3]));
        }
        if r.4 != g[4] {
            errs.push(format!("detection_type: rust '{}' vs golden '{}'", r.4, g[4]));
        }
        if !errs.is_empty() && mismatches.len() < 20 {
            mismatches.push(format!("({}|{}): {}", r.0, r.1, errs.join("; ")));
        }
    }

    assert!(
        mismatches.is_empty(),
        "L6 decoy mismatches ({} shown):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
